let text21 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
let length = text21.length;
console.log(length);
let text22 = "Please visit Microsoft and Microsoft!";
let newText = text22.replace("Microsoft", "W3Schools");
console.log(newText);
let text1 = "Hello World!";
let text2 = text1.toUpperCase();
let text3 = text1.toLowerCase();
console.log(text2);
console.log(text3);